server:
  port: 8004
spring:
  datasource:
    url: jdbc:mysql://39.105.25.16:3306/pcs?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: yang1290
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

security:
  oauth2:
    resource:
      user-info-uri: http://10.103.246.113:8001/pcs-auth/oauth/principal
    client:
      access-token-uri: http://10.103.246.113:8001/pcs-auth/oauth/token
      grant-type: client_credentials,password
